#!C:/Program Files (x86)/Git/bin/sh
echo "sup"
mkdir "stupid"
exit 0


C:\Users\jedderfrank\AppData\Roaming\npm\

C:\Users\jedderfrank\AppData\Roaming\npm\


;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;c
:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;
c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;
c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;
C:\Program Files\TortoiseSVN\bin;F:\Programs\Calibre2\;
C:\Ruby193\bin;C:\Program Files (x86)\git\bin;
C:\Program Files (x86)\git\cmd;C:\DevKit\bin;C:\Heroku\bin;C:\PostgreSQL\9.1\bin;C:\PostgreSQL\9.1\lib;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Meteor\;C:\Program Files (x86)\Meteor\bin